from gateparser.parser import GateBIOParser


def test_parse():
    parsed_xml = GateBIOParser('example-data/example-gate-export.xml', encoding='windows-1252',
                               annotation_spec='GateDocument.AnnotationSet',
                               node_spec='GateDocument.TextWithNodes',
                               text_spec='GateDocument.TextWithNodes')
    
    labels = ['O','O','O','O','O','O','O','O','B-FullName','I-FullName','O','I-UserIDGeneric','O','O','O','B-TelNumber','I-TelNumber','I-TelNumber','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','B-FullName','I-FullName','O','I-UserIDGeneric','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O','O']
    tokens = [' ','*','11','.','11','.','2011','01:54:01','Kimb','Helper','(','HELPER',')','Tel','.','121','12345678','12345','*','1234','-','12345',';','  ','123456',';',' ','ABCD','-','ABC5',';',' ','Y','-','1222','-','Y','-','1222',';','Shop',' ','VINE','PP','*','OOGGAAA',' ','AAA6BBB','*','AAAAA','  ','PL1181','*','*','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','*','*','The','wire','label','from','wire','0000','-','0000','and','0000','-','0000','of','1234VV','are','exchanged','*','at','both','ends','of','the','TE','.','*','The','length','of','the','two','wire','are','in','line','with','definition','.','*','To','install','the','right','tone','at','the','lefts','position','at','the','VTï¿½s','the','wire','*','labels','must','be','change','the','position','between','the','two','wire','.','*','*','WD','T246','-','91104','-','01','*','*','For','more','information','see','appendix','*','11','.','11','.','2011','22:22:22','Jojojos','Oatiest','(','OATIEST',')','*','Job','done','and','inspected','.','Jobcard','(','1234121234123',')','covered','by','Molio','Doing','  ','1','.','1',' ','Interventionnumber','111111']
    assert parsed_xml.BIO['labels'] == labels
    assert parsed_xml.BIO['tokens'] == tokens
